name: quiz_khel
description: "A new Flutter project that converts scanned text into MCQs and quizzes users."

# This line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# App version
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and animations
  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9

  # Image handling and AI
  image_picker: ^1.1.2
  google_ml_kit: ^0.20.0
  http: ^1.4.0

  # State management
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # If you have assets (images, fonts), list them here:
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
