// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09a8mwBr3gAhgUWf9f2R_ExZ7-mfAgZs',
    appId: '1:95589031508:web:8387c394333108413797c1',
    messagingSenderId: '95589031508',
    projectId: 'quiz-khel',
    authDomain: 'quiz-khel.firebaseapp.com',
    storageBucket: 'quiz-khel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEpZ9trIQDjU5a4P2gl4S4JeO0lk3zLV8',
    appId: '1:95589031508:android:25c39094aabf71733797c1',
    messagingSenderId: '95589031508',
    projectId: 'quiz-khel',
    storageBucket: 'quiz-khel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_KrxMcqS3LBI74gjQbOWRgFcyCGLuMo',
    appId: '1:95589031508:ios:a6a57514ee38b6e03797c1',
    messagingSenderId: '95589031508',
    projectId: 'quiz-khel',
    storageBucket: 'quiz-khel.firebasestorage.app',
    iosBundleId: 'com.example.quizKhel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2_KrxMcqS3LBI74gjQbOWRgFcyCGLuMo',
    appId: '1:95589031508:ios:a6a57514ee38b6e03797c1',
    messagingSenderId: '95589031508',
    projectId: 'quiz-khel',
    storageBucket: 'quiz-khel.firebasestorage.app',
    iosBundleId: 'com.example.quizKhel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC09a8mwBr3gAhgUWf9f2R_ExZ7-mfAgZs',
    appId: '1:95589031508:web:066049e7e4000a6a3797c1',
    messagingSenderId: '95589031508',
    projectId: 'quiz-khel',
    authDomain: 'quiz-khel.firebaseapp.com',
    storageBucket: 'quiz-khel.firebasestorage.app',
  );
}
